global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'task-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['task-service:8080']

  - job_name: 'task-worker'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['task-worker:8081']
